language: python

jobs:
  include:
    - name: "Python 3.6 on Linux"
      python: "3.6"
      os: "linux"
      env:
        - PYTHON=python3
        - PIP=pip3
    - name: "Python 3.7 on Linux"
      python: "3.7"
      os: "linux"
      env:
        - PYTHON=python3
        - PIP=pip3
    - name: "Python 3.8 on Linux"
      python: "3.8"
      os: "linux"
      env:
        - PYTHON=python3
        - PIP=pip3
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      env:
        - PYTHON=python3
        - PIP=pip3
    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python --version
      env:
        - PYTHON=python
        - PIP=pip

install:
  - $PYTHON --version
  - $PIP install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

script:
  - $PYTHON --version
  - $PYTHON main.py test
