language: python

jobs:
  include:
    - name: "Python 3.6 on Linux"
      python: "3.6"
      os: "linux"
    - name: "Python 3.7 on Linux"
      python: "3.7"
      os: "linux"
    - name: "Python 3.8 on Linux"
      python: "3.8"
      os: "linux"
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell

install:
  - pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

script:
  - python --version
  - python main.py test
